#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
qspi-configurator config_usbdev usbdev-configurator config device-configurator capsense-configurator capsense-tuner bsp-assistant modlibs library-manager dfuh-tool config_ezpd ez-pd-configurator smartio-configurator seglcd-configurator edge-protect-configurator :
	make -C Hello_World $@

config_bt bt-configurator config_lin lin-configurator secure-policy-configurator :
	$(error $@ configurator cannot be executed at the application level. Run this command from the desired project directory.)

.PHONY: config_bt bt-configurator config_lin lin-configurator qspi-configurator config_usbdev usbdev-configurator config device-configurator capsense-configurator capsense-tuner bsp-assistant modlibs library-manager dfuh-tool config_ezpd ez-pd-configurator smartio-configurator seglcd-configurator secure-policy-configurator edge-protect-configurator
